import { createAuditEvent } from '../../../core/src/state.js';
import type { CoverageGap } from '../../../core/src/types.js';
import type { CollectionTask, MCPResponseEnvelope, PlanCollectionData, PlanCollectionInput, CollectionStatusData, GetCollectionStatusInput, ListCoverageGapsData, ListCoverageGapsInput } from '../contracts.js';
import { getRegistryFreshness, getSourceMethodRegistryEntry, validateRegistryEntryDates } from '../source-method-registry.js';

export function enrichCoverageGap(gap: CoverageGap): CoverageGap {
  if (gap.whyItBlocks && gap.recommendedNextAction && gap.collectionMode) return gap;
  const mapping: Record<string, { whyItBlocks: string; recommendedNextAction: string; collectionMode: CoverageGap['collectionMode'] }> = {
    missing_income_source: { whyItBlocks: 'Income inventory is incomplete, so the agent cannot safely know what must be reported.', recommendedNextAction: 'tax.sources.plan_collection', collectionMode: 'browser_assist' },
    missing_withholding_record: { whyItBlocks: 'Explicit withholding/prepaid tax is missing, so credits and submission readiness remain unreliable.', recommendedNextAction: 'tax.withholding.list_records', collectionMode: 'browser_assist' },
    missing_expense_evidence: { whyItBlocks: 'Expense claims cannot be defended or applied confidently without linked evidence.', recommendedNextAction: 'tax.import.upload_documents', collectionMode: 'export_ingestion' },
    missing_deduction_fact: { whyItBlocks: 'Required taxpayer facts for deductions/credits are still missing, so adjustment decisions are incomplete.', recommendedNextAction: 'tax.profile.list_missing_facts', collectionMode: 'fact_capture' },
    missing_hometax_comparison: { whyItBlocks: 'Submission assist cannot proceed until draft values are compared against HomeTax-observed values.', recommendedNextAction: 'tax.filing.compare_with_hometax', collectionMode: 'browser_assist' },
  };
  const matched = mapping[gap.gapType] ?? { whyItBlocks: 'A material coverage gap still blocks progress.', recommendedNextAction: gap.recommendedNextAction ?? 'tax.sources.plan_collection', collectionMode: 'export_ingestion' as const };
  return { ...gap, whyItBlocks: gap.whyItBlocks ?? matched.whyItBlocks, recommendedNextAction: gap.recommendedNextAction ?? matched.recommendedNextAction, collectionMode: gap.collectionMode ?? matched.collectionMode };
}

export function buildRegistryFreshnessSurface(sourceCategory: string, targetArtifactType: string, nowIso = new Date().toISOString()) {
  const entry = getSourceMethodRegistryEntry(sourceCategory, targetArtifactType);
  if (!entry) return undefined;
  const freshness = getRegistryFreshness(entry, nowIso);
  const dateWarnings = validateRegistryEntryDates(entry, nowIso);
  const methodFreshnessWarning = dateWarnings.length > 0 ? `Registry date anomaly: ${dateWarnings.join(', ')}` : freshness.reverifyRecommended ? `Registry guidance is stale relative to freshness window; re-verify before relying on ${entry.preferredMethod}.` : undefined;
  return { registryEntryId: entry.entryId, registryVerifiedAt: entry.verifiedAt, registryReviewAfter: entry.reviewAfter, reverifyRecommended: freshness.reverifyRecommended || dateWarnings.length > 0, knownInvalidMethods: entry.knownInvalidMethods, methodFreshnessWarning };
}

export function buildGapNextActionPlan(gaps: CoverageGap[]) {
  const enriched = gaps.filter((gap) => gap.state === 'open').map(enrichCoverageGap);
  const rank = (gap: CoverageGap) => (gap.collectionMode === 'browser_assist' ? 0 : gap.collectionMode === 'export_ingestion' ? 1 : 2) * 10 + (gap.severity === 'high' ? 0 : gap.severity === 'medium' ? 1 : 2);
  const prioritizedGap = [...enriched].sort((a, b) => rank(a) - rank(b))[0];
  const nextActionPlan = prioritizedGap ? { gapId: prioritizedGap.gapId, gapType: prioritizedGap.gapType, recommendedNextAction: prioritizedGap.recommendedNextAction ?? 'tax.sources.plan_collection', collectionMode: (prioritizedGap.collectionMode === 'direct_connector' ? 'browser_assist' : (prioritizedGap.collectionMode ?? 'export_ingestion')) as 'browser_assist' | 'export_ingestion' | 'fact_capture', whyThisIsNext: prioritizedGap.whyItBlocks ?? prioritizedGap.description } : undefined;
  return { enriched, prioritizedGap, nextActionPlan };
}

export function resolveCollectionProfile(params: { facts?: unknown[]; bookkeepingMode?: string; taxpayerPosture?: string }) {
  if (params.bookkeepingMode === 'double_entry') return 'double_entry_service' as const;
  if (params.taxpayerPosture === 'pure_business') return 'it_freelancer' as const;
  return 'generic_fallback' as const;
}

export function buildCollectionTasksForProfile(profile: 'it_freelancer' | 'double_entry_service' | 'generic_fallback', workspaceId: string, filingYear: number, verifiedAt?: string): CollectionTask[] {
  const task = (base: CollectionTask): CollectionTask => {
    const entry = getSourceMethodRegistryEntry(base.sourceCategory, base.targetArtifactType);
    const freshness = buildRegistryFreshnessSurface(base.sourceCategory, base.targetArtifactType);
    const freshnessMeta = entry ? getRegistryFreshness(entry) : undefined;
    return { ...base, whyThisSourceNow: `${base.whyThisSourceNow}${entry ? ` Preferred method: ${entry.preferredMethod}.` : ''}${freshness?.reverifyRecommended ? ' Re-verify recommended before relying on this method guidance.' : ''}${freshness?.methodFreshnessWarning ? ` ${freshness.methodFreshnessWarning}` : ''}`, portalPathHints: [...base.portalPathHints, ...(freshness?.knownInvalidMethods?.length ? [`Known invalid methods: ${freshness.knownInvalidMethods.map((item) => `${item.method} (invalid as of ${item.invalidAsOf})`).join(', ')}`] : []), ...(freshnessMeta ? [`Registry verifiedAt=${entry?.verifiedAt}; reviewAfter=${entry?.reviewAfter}; expiresAt=${freshnessMeta.expiresAt}`] : [])], verifiedAt: verifiedAt ?? entry?.verifiedAt, ...freshness };
  };
  const tasks: CollectionTask[] = [
    task({ taskId: `task_${workspaceId}_hometax_withholding_${filingYear}`, sourceCategory: 'hometax', collectionMode: 'browser_assist', targetArtifactType: 'withholding_receipt', acceptedArtifactShapes: ['HomeTax official withholding tax receipt print/PDF', 'HomeTax printable official certificate/export rendered as PDF'], rejectedArtifactShapes: ['withholding list XLS only without the official print/PDF', 'payer-side informal screenshot without official receipt details', 'summary-only withholding table without official printable form'], portalPathHints: ['HomeTax > MyHomeTax > 지급명세서/원천징수영수증', 'Use print/PDF output, not only table list view'], whyThisSourceNow: 'Official withholding receipts are the highest-authority prepaid tax source and block Tier A filing if missing.', userCheckpointBrief: 'Log into HomeTax and let the external browser agent collect the official withholding receipt PDF/print.', sufficiencyRule: 'HomeTax withholding is sufficient only with the official PDF/print or equivalent official printable certificate. XLS/list/summary-only is insufficient_artifact.', blockingIfMissing: true, fallbackTaskIds: [`task_${workspaceId}_hometax_packet_${filingYear}`, `task_${workspaceId}_manual_income_facts_${filingYear}`], verifiedAt, nextRecommendedAction: 'tax.sources.connect' }),
    task({ taskId: `task_${workspaceId}_hometax_notice_${filingYear}`, sourceCategory: 'hometax', collectionMode: 'browser_assist', targetArtifactType: 'filing_guidance_notice', acceptedArtifactShapes: ['HomeTax 신고안내정보 official page print/PDF', 'official notice export captured with year and taxpayer context'], rejectedArtifactShapes: ['free-text summary from memory', 'cropped screenshot without year/taxpayer context'], portalPathHints: ['HomeTax > 종합소득세 > 신고도움서비스 / 신고안내정보'], whyThisSourceNow: 'The filing guidance notice helps confirm prefilled scope, notices, and supported-path assumptions early.', userCheckpointBrief: 'Collect the official HomeTax filing guidance notice print/PDF for the filing year.', sufficiencyRule: 'The notice must preserve year and taxpayer context; memory-based summaries are not enough.', blockingIfMissing: true, fallbackTaskIds: [`task_${workspaceId}_hometax_withholding_${filingYear}`], verifiedAt, nextRecommendedAction: 'tax.sources.connect' }),
    task({ taskId: `task_${workspaceId}_hometax_packet_${filingYear}`, sourceCategory: 'hometax', collectionMode: 'export_ingestion', targetArtifactType: 'year_end_tax_bundle', acceptedArtifactShapes: ['연말정산 간소화 PDF bundle', 'official HomeTax export bundle with named deduction documents', '2023 season packet with official PDFs attached'], rejectedArtifactShapes: ['summary-only bundle cover page', 'manually retyped deduction totals only'], portalPathHints: ['HomeTax > 연말정산간소화 > PDF 내려받기 / 일괄 다운로드', 'For older season packets, keep attachment filenames and packet date context'], whyThisSourceNow: 'The HomeTax packet is a high-leverage first-wave export when official browser prints are blocked or an older season packet already exists.', userCheckpointBrief: 'Upload the official HomeTax packet or simplification bundle with filenames and season context intact.', sufficiencyRule: 'Bundle summaries help deduction overview but do not replace itemized business expense evidence.', blockingIfMissing: false, fallbackTaskIds: [`task_${workspaceId}_card_itemized_${filingYear}`, `task_${workspaceId}_conditional_supporting_docs_${filingYear}`], verifiedAt, nextRecommendedAction: 'tax.import.import_hometax_materials' }),
    task({ taskId: `task_${workspaceId}_card_itemized_${filingYear}`, sourceCategory: 'card_statement', collectionMode: 'export_ingestion', targetArtifactType: 'card_itemized_detail', acceptedArtifactShapes: ['itemized card statement PDF/CSV with line items, merchant, date, and amount', 'official card transaction detail export'], rejectedArtifactShapes: ['summary-only card monthly totals', 'bundle cover sheet without line items'], portalPathHints: ['Request itemized detail only when expense review needs line-item support'], whyThisSourceNow: 'Itemized card detail is the right follow-up when expense evidence is still weak after first-wave HomeTax collection.', userCheckpointBrief: 'Provide itemized card detail, not just monthly totals or summary bundles.', sufficiencyRule: 'Summary-only card bundles are insufficient; line-item detail is required for business-expense review.', blockingIfMissing: false, fallbackTaskIds: [`task_${workspaceId}_petty_receipts_${filingYear}`], verifiedAt, nextRecommendedAction: 'tax.import.upload_documents' }),
    task({ taskId: `task_${workspaceId}_secure_mail_${filingYear}`, sourceCategory: 'secure_mail', collectionMode: 'export_ingestion', targetArtifactType: 'secure_mail_attachment', acceptedArtifactShapes: ['actual downloadable attachment from secure mail', 'attachment after password checkpoint is completed'], rejectedArtifactShapes: ['password-gated secure mail HTML only', 'secure mail screenshot without downloaded attachment'], portalPathHints: ['Secure mail HTML itself is usually not evidence; retrieve the attachment or clear the password gate first'], whyThisSourceNow: 'Use this only when the source delivers evidence through secure mail rather than a normal export portal.', userCheckpointBrief: 'Complete the attachment/password checkpoint first, then upload the actual attachment.', sufficiencyRule: 'Password-gated secure mail HTML is not importable evidence. The attachment itself is required.', blockingIfMissing: false, fallbackTaskIds: [`task_${workspaceId}_payroll_detail_${filingYear}`], verifiedAt, nextRecommendedAction: 'tax.import.upload_documents' }),
    task({ taskId: `task_${workspaceId}_resident_register_${filingYear}`, sourceCategory: 'government_record', collectionMode: 'export_ingestion', targetArtifactType: 'resident_register', acceptedArtifactShapes: ['official resident register PDF/print'], rejectedArtifactShapes: ['typed household summary without official document'], portalPathHints: ['Request only if household/address-linked deduction review actually needs it'], whyThisSourceNow: 'Resident register should be requested only as conditional proof, not as default first-wave evidence.', userCheckpointBrief: 'Upload the official resident register only if the deduction review explicitly asks for household/address proof.', sufficiencyRule: 'Only the official document is sufficient for address/household proof.', blockingIfMissing: false, fallbackTaskIds: [`task_${workspaceId}_conditional_supporting_docs_${filingYear}`], verifiedAt, nextRecommendedAction: 'tax.import.upload_documents' }),
    task({ taskId: `task_${workspaceId}_health_insurance_${filingYear}`, sourceCategory: 'health_insurance', collectionMode: 'export_ingestion', targetArtifactType: 'health_insurance_payment_history', acceptedArtifactShapes: ['official health insurance payment history PDF/export'], rejectedArtifactShapes: ['payment screenshot without payer/period context'], portalPathHints: ['Collect only if deduction or reconciliation logic specifically needs health-insurance payment proof'], whyThisSourceNow: 'Health-insurance history is a targeted conditional source, not a first-wave default.', userCheckpointBrief: 'Export the official payment history only if MCP specifically asks for health-insurance proof.', sufficiencyRule: 'History should preserve payer, period, and amount context.', blockingIfMissing: false, fallbackTaskIds: [`task_${workspaceId}_conditional_supporting_docs_${filingYear}`], verifiedAt, nextRecommendedAction: 'tax.import.upload_documents' }),
    task({ taskId: `task_${workspaceId}_telecom_${filingYear}`, sourceCategory: 'telecom', collectionMode: 'export_ingestion', targetArtifactType: 'telecom_payment_history', acceptedArtifactShapes: ['itemized telecom bill/payment history PDF'], rejectedArtifactShapes: ['simple payment confirmation without service/use detail'], portalPathHints: ['Collect only when business-use telecom review needs itemized history'], whyThisSourceNow: 'Telecom history is useful only for narrow business-use review, so keep it targeted.', userCheckpointBrief: 'Upload an itemized telecom statement only if business-use review explicitly needs it.', sufficiencyRule: 'Simple paid/unpaid summaries are insufficient; itemized statement context is needed.', blockingIfMissing: false, fallbackTaskIds: [`task_${workspaceId}_manual_income_facts_${filingYear}`], verifiedAt, nextRecommendedAction: 'tax.import.upload_documents' }),
    task({ taskId: `task_${workspaceId}_rent_contract_${filingYear}`, sourceCategory: 'housing', collectionMode: 'export_ingestion', targetArtifactType: 'rent_contract', acceptedArtifactShapes: ['signed rent contract PDF/scan with parties and address visible'], rejectedArtifactShapes: ['chat summary of rent terms only'], portalPathHints: ['Collect only when rent-related deduction or business-use location review actually needs it'], whyThisSourceNow: 'Rent contract is conditional support, not a default first-wave request.', userCheckpointBrief: 'Provide the signed contract only if the rent deduction or business-use review requires it.', sufficiencyRule: 'The document must show parties, term, and address details.', blockingIfMissing: false, fallbackTaskIds: [`task_${workspaceId}_conditional_supporting_docs_${filingYear}`], verifiedAt, nextRecommendedAction: 'tax.import.upload_documents' }),
    task({ taskId: `task_${workspaceId}_petty_receipts_${filingYear}`, sourceCategory: 'local_documents', collectionMode: 'export_ingestion', targetArtifactType: 'petty_receipts_bundle', acceptedArtifactShapes: ['curated petty receipts bundle with date/merchant/amount visible'], rejectedArtifactShapes: ['unsorted phone photo dump with no scope note'], portalPathHints: ['Use only after higher-authority sources and itemized statements are exhausted'], whyThisSourceNow: 'Petty receipts are a last-mile evidence bundle, not the first source to request.', userCheckpointBrief: 'Upload a curated, scoped receipt bundle rather than a raw dump of every image.', sufficiencyRule: 'Bundle should be curated and scoped to the claimed expense set.', blockingIfMissing: false, fallbackTaskIds: [`task_${workspaceId}_manual_income_facts_${filingYear}`], verifiedAt, nextRecommendedAction: 'tax.import.upload_documents' }),
    task({ taskId: `task_${workspaceId}_payroll_detail_${filingYear}`, sourceCategory: 'payroll', collectionMode: 'export_ingestion', targetArtifactType: 'payroll_payment_detail', acceptedArtifactShapes: ['official payroll payment detail PDF/export'], rejectedArtifactShapes: ['salary transfer screenshot without payroll breakdown'], portalPathHints: ['Collect only when salary-side reconciliation needs more detail than the withholding record gives'], whyThisSourceNow: 'Payroll detail is a targeted reconciliation source, not a general first-wave request.', userCheckpointBrief: 'Provide payroll detail only if salary reconciliation is still under-specified.', sufficiencyRule: 'The detail should preserve pay period and pay item breakdowns.', blockingIfMissing: false, fallbackTaskIds: [`task_${workspaceId}_secure_mail_${filingYear}`], verifiedAt, nextRecommendedAction: 'tax.import.upload_documents' }),
    task({ taskId: `task_${workspaceId}_conditional_supporting_docs_${filingYear}`, sourceCategory: 'conditional_supporting_documents', collectionMode: 'fact_capture', targetArtifactType: 'conditional_deduction_support', acceptedArtifactShapes: ['resident registration certificate when address/family deduction needs proof', 'official donation receipt PDF', 'official disability-related proof document'], rejectedArtifactShapes: ['generic photo of a paper without identifying fields', 'chat message claiming eligibility without supporting document'], portalPathHints: ['Collect only if a deduction fact or review item specifically asks for it'], whyThisSourceNow: 'Conditional supporting documents should be requested only when a concrete deduction fact remains unresolved.', userCheckpointBrief: 'Answer the targeted deduction question first; upload the exact official proof only if MCP asks for it.', sufficiencyRule: 'Only the exact official proof tied to the unresolved deduction fact should be requested.', blockingIfMissing: false, fallbackTaskIds: [], verifiedAt, nextRecommendedAction: 'tax.profile.upsert_facts' }),
    task({ taskId: `task_${workspaceId}_manual_income_facts_${filingYear}`, sourceCategory: 'fact_capture', collectionMode: 'fact_capture', targetArtifactType: 'income_scope_confirmation', acceptedArtifactShapes: ['structured taxpayer fact response naming income streams and missing official exports'], rejectedArtifactShapes: ['vague statement like more files later', 'unstructured request to upload everything'], portalPathHints: ['Use only as fallback when official HomeTax materials are temporarily unavailable'], whyThisSourceNow: 'Fact capture is fallback only; it cannot replace authoritative withholding material for Tier A submission readiness.', userCheckpointBrief: 'Confirm which income streams exist and which official exports are still missing.', sufficiencyRule: 'This confirms scope only; it does not replace authoritative evidence.', blockingIfMissing: false, fallbackTaskIds: [], verifiedAt, nextRecommendedAction: 'tax.profile.upsert_facts' }),
  ];
  return profile === 'generic_fallback' ? tasks : tasks;
}

export function taxSourcesPlanCollectionPolicy(input: PlanCollectionInput): MCPResponseEnvelope<PlanCollectionData> {
  const prioritizedGap = enrichCoverageGap({ gapId: `gap_plan_${input.workspaceId}_hometax`, workspaceId: input.workspaceId, gapType: 'missing_income_source', severity: 'high', description: 'HomeTax authoritative materials have not been collected yet.', affectedArea: 'income_inventory', affectedDomains: ['incomeInventory'], materiality: 'high', blocksEstimate: true, blocksDraft: true, blocksSubmission: true, recommendedNextSource: 'hometax', relatedSourceIds: [], state: 'open' });
  const collectionTasks = buildCollectionTasksForProfile('it_freelancer', input.workspaceId, input.filingYear);
  const nextActionPlan: PlanCollectionData['nextActionPlan'] = { gapId: prioritizedGap.gapId, gapType: prioritizedGap.gapType, recommendedNextAction: collectionTasks[0]?.nextRecommendedAction ?? prioritizedGap.recommendedNextAction!, collectionMode: (prioritizedGap.collectionMode === 'direct_connector' ? 'browser_assist' : prioritizedGap.collectionMode!) as 'browser_assist' | 'export_ingestion' | 'fact_capture', whyThisIsNext: prioritizedGap.whyItBlocks! };
  const audit = createAuditEvent({ workspaceId: input.workspaceId, eventType: 'source_planned', actorType: 'agent', summary: 'Planned recommended collection sources for the workspace.' });
  return { ok: true, status: 'completed', data: { recommendedSources: [{ sourceType: 'hometax', priority: 'high', rationale: 'Highest-value authoritative filing source and best first checkpoint.', collectionMode: 'browser_assist', likelyCheckpoints: ['source_consent', 'authentication', 'collection_blocker'], fallbackOptions: ['Import HomeTax-exported files manually', 'Proceed with local evidence and draft a partial workspace'] }, { sourceType: 'local_documents', priority: 'medium', rationale: 'Useful for receipts, statements, and evidence gaps after HomeTax collection.', collectionMode: 'export_ingestion', likelyCheckpoints: ['source_consent'], fallbackOptions: ['Upload a targeted set of files', 'Answer focused evidence questions'] }], collectionTasks, expectedValueBySource: { hometax: 'High authority for filing materials and cross-checks', local_documents: 'High practical value for supporting evidence and missing exports' }, likelyUserCheckpoints: ['source_consent', 'authentication', 'collection_blocker'], fallbackPathSuggestions: ['Use exported statements when live collection is blocked', 'Continue with partial collection and targeted follow-up'], prioritizedGap, nextActionPlan }, progress: { phase: 'source_planning', step: 'rank_next_sources', percent: 100 }, nextRecommendedAction: 'tax.sources.connect', audit: { eventType: audit.eventType, eventId: audit.eventId ?? audit.auditEventId ?? 'evt_source_planned' } };
}
